/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>



extern "C" {

void array_sort(uint32_t *array, size_t len);

uint32_t array_sum(const uint32_t *array, size_t len);

} // extern "C"
